In [ ]:
import pandas as pd # pandas representated as pd (typical in programming)
import numpy as np # numpy representated as np (typical in programming)
import src
import src.data_converter as converter
from src.model import DecisionTree # decision tree calls
# from sklearn.model_selection import train_test_split
#from sklearn.metrics import confusion_matrix # confusion matrix module
#import seaborn as sns # to plot confusion matrix
import matplotlib.pyplot as plt # to plot confusion matrix
import pprint #prints tree representation in a neat format

data = pd.read_csv("data/car_evaluation.csv", names= ["buying price", "maintenance cost", "number of doors", "number of persons", "lug_boot", "safety", "decision"])

# train test split of data
shuffled_data = data.sample(frac = 1, random_state=42)

# Define a size for your train set 
train_size = int(0.9 * len(data))

# Split your dataset 
train_df = shuffled_data[:train_size]
test_df = shuffled_data[train_size:]
train = converter.dataframe_to_dict(train_df)
test = converter.dataframe_to_dict(test_df)

label = {"decision": train["decision"]}
features = train
del features["decision"]
train_data = {"features": features, "label": label}

tree = DecisionTree(7)
d = {'buying price': train_data["features"]['buying price'],
 'maintenance cost': train_data["features"]['maintenance cost'],
 'number of doors': train_data["features"]['number of doors'], 
 'number of persons': train_data["features"]['number of persons'],
 'lug_boot':train_data["features"]['lug_boot'],
 'safety': train_data["features"]['safety']}

l = {'decision':train_data["label"]['decision']}

m = tree.fit(d, l)
# print(tree.representation)

prediction_list = []
true_list = []
accuracy_list = []
correct_list = []
wrong_list = []
for i in range(len(test_df)):
    feature_record = dict(test_df.iloc[i])
    label = feature_record["decision"]
    del feature_record["decision"]
    prediction = tree.predict(feature_record)
    prediction_list.append(prediction)
    true_list.append(label)
    correct_list.append(label)
    if label == prediction:
        accuracy_list.append(1)
    else:
        accuracy_list.append(0)

prediction_list = []
true_list = []
accuracy_list = []
correct_list = []
wrong_list = []
for i in range(len(test_df)):
    feature_record = dict(test_df.iloc[i])
    label = feature_record["decision"]
    del feature_record["decision"]
    prediction = tree.predict(feature_record)
    prediction_list.append(prediction)
    true_list.append(label)
    correct_list.append(label)
    if label == prediction:
        accuracy_list.append(1)
    else:
        accuracy_list.append(0)

print("accuracy", sum(accuracy_list)/ len(accuracy_list))

In [ ]:
# -- the resulting confusion matrix for varying parameter definitions

6 1
accuracy 0.7222222222222222
confusion matrix  [0 0 0 0]
confusion matrix  [[ 0  1  0  0]
 [ 0 13  0  0]
 [ 0  0  0  0]
 [ 0  4  0  0]]

6 5
accuracy 0.7222222222222222
confusion matrix  [0 0 0 0]
confusion matrix  [[ 0  4  0  0]
 [ 0 13  0  0]
 [ 0  0  0  0]
 [ 0  1  0  0]]

6 10
accuracy 0.6551724137931034
confusion matrix  [0 0 0 0]
confusion matrix  [[ 0  0 22  0]
 [ 0  0  2  0]
 [ 0  0 57  0]
 [ 0  0  6  0]]

6 15
accuracy 0.6923076923076923
confusion matrix  [0 0 0 0]
confusion matrix  [[  0   0   0  10]
 [  0   0   0  11]
 [  0   0   0  59]
 [  0   0   0 180]]

5 5
accuracy 0.6551724137931034
confusion matrix  [0 0 0 0]
confusion matrix  [[ 0  6  0  0]
 [ 0 57  0  0]
 [ 0  2  0  0]
 [ 0 22  0  0]]
<matplotlib.axes._subplots.AxesSubplot at 0x7fac7c0e2b50>

5 10
accuracy 0.6473988439306358
confusion matrix  [112  10   7  44]
confusion matrix  [[112   0   0   0]
 [ 10   0   0   0]
 [  7   0   0   0]
 [ 44   0   0   0]]

5 15
accuracy 0.6923076923076923
confusion matrix  [0 0 0 0]
confusion matrix  [[  0  59   0   0]
 [  0 180   0   0]
 [  0  11   0   0]
 [  0  10   0   0]]
4 5
 accuracy 0.6551724137931034
confusion matrix  [0 0 0 0]
confusion matrix  [[ 0  0  0  2]
 [ 0  0  0  6]
 [ 0  0  0 22]
 [ 0  0  0 57]]